# Generated by Django 4.1.5 on 2023-01-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=20)),
                ('location', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'charity',
            },
        ),
    ]
