# Generated by Django 4.1.5 on 2023-01-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='charityapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=70)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'charity',
            },
        ),
        migrations.DeleteModel(
            name='Charity',
        ),
    ]
